version: "3"
services:
  tododb:
    image: postgres:13.4
    container_name: "tododb"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo-api
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data